name=XLOT-QuadSwitch
version=1.0.2
author=XLOT
maintainer=XLOT
sentence=Library for XLOT-QuadSwitch RGB button module.
paragraph=Read four switch states and control four RGB LEDs over I2C. Designed for XLOT boards and Arduino-compatible ESP32 projects.
category=Signal Input/Output
url=http://www.xlot.tech
architectures=esp32
includes=XLOT_QuadSwitch.h
